#!/bin/bash
opfk
case $1 in
    -p) 
        screen -x -S ${FKP:-freekill} -p 0 -X stuff "lsplayer\n"
        sleep 1
        h=`grep -n "online" $FKS/freekill.log | tail -1 |awk -F : '{print $1}'`
        b=`grep -n "online" $FKS/freekill.log | tail -1 |awk '{print $5}'`
        if [ -z $h ] || [ -z $b ]
        then
            echo "没有在线玩家"
            exit 1
        fi
        l=`expr ${h} + ${b}`
        echo $b个在线玩家:
        head -$l $FKS/freekill.log | tail -$b
        ;;
    -r) 
        screen -x -S ${FKP:-freekill} -p 0 -X stuff "lsroom\n"
        sleep 1
        h=`grep -n "running" $FKS/freekill.log | tail -1 |awk -F : '{print $1}'`
        b=`grep -n "running" $FKS/freekill.log | tail -1 |awk '{print $5}'`
        if [ -z $h ] || [ -z $b ]
        then
            echo "没有在线房间"
            exit 1
        fi
        l=`expr ${h} + ${b}`
        echo $b个在线房间:
        head -$l $FKS/freekill.log | tail -$b
        ;;
    *)
        echo "Usage: lsfk [-p|-r]"
        echo "-p: 显示在线玩家"
        echo "-r: 显示在线房间"
        ;;
esac
true > $FKS/freekill.log